export const ADD_TO_CART_ITEM = 'ADD_TO_CART_ITEM' ;

export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const SAVE_SHIPPING_CART_ADDRESS = 'SAVE_SHIPPING_CART_ADDRESS';

export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD';

export const CART_EMPTY = 'CART_EMPTY';